links:
    - product: firefox
      url: https://bugzilla.mozilla.org/show_bug.cgi?id=1858035
      results:
        - test: observable-constructor.any.html
          subtest: Observable constructor
        - test: observable-constructor.any.html
          subtest: subscribe() can be called with no arguments
        - test: observable-constructor.any.html
          subtest: Errors thrown in the initializer that are not handled by the subscription are reported to the global
        - test: observable-constructor.any.html
          subtest: Errors thrown by initializer function after subscriber is closed by completion are reported
    - product: firefox
      url: https://bugzilla.mozilla.org/show_bug.cgi?id=1863864
      results:
        - test: observable-constructor.any.html
          subtest: Subscriber interface is not constructible
        - test: observable-constructor.any.html
          subtest: Observable constructor calls initializer on subscribe
        - test: observable-constructor.any.html
          subtest: Observable error path called synchronously
        - test: observable-constructor.any.html
          subtest: Observable should error if initializer throws
        - test: observable-constructor.any.html
          subtest: Subscription does not emit values after completion
        - test: observable-constructor.any.html
          subtest: Subscription does not emit values after error
        - test: observable-constructor.any.html
          subtest: Completing or nexting a subscriber after an error does nothing
        - test: observable-constructor.any.html
          subtest: Errors pushed to the subscriber that are not handled by the subscription are reported to the global
        - test: observable-constructor.any.html
          subtest: Subscription reports errors that are pushed after subscriber is closed by completion
        - test: observable-constructor.any.html
          subtest: Errors thrown by initializer function after subscriber is closed by error are reported
        - test: observable-constructor.any.html
          subtest: Errors pushed by initializer function after subscriber is closed by error are reported
        - test: observable-constructor.any.worker.html
          subtest: Observable constructor
        - test: observable-constructor.any.worker.html
          subtest: Subscriber interface is not constructible
        - test: observable-constructor.any.worker.html
          subtest: subscribe() can be called with no arguments
        - test: observable-constructor.any.worker.html
          subtest: Observable constructor calls initializer on subscribe
        - test: observable-constructor.any.worker.html
          subtest: Observable error path called synchronously
        - test: observable-constructor.any.worker.html
          subtest: Observable should error if initializer throws
        - test: observable-constructor.any.worker.html
          subtest: Subscription does not emit values after completion
        - test: observable-constructor.any.worker.html
          subtest: Subscription does not emit values after error
        - test: observable-constructor.any.worker.html
          subtest: Completing or nexting a subscriber after an error does nothing
        - test: observable-constructor.any.worker.html
          subtest: Errors pushed to the subscriber that are not handled by the subscription are reported to the global
        - test: observable-constructor.any.worker.html
          subtest: Errors thrown in the initializer that are not handled by the subscription are reported to the global
        - test: observable-constructor.any.worker.html
          subtest: Subscription reports errors that are pushed after subscriber is closed by completion
        - test: observable-constructor.any.worker.html
          subtest: Errors thrown by initializer function after subscriber is closed by completion are reported
        - test: observable-constructor.any.worker.html
          subtest: Errors thrown by initializer function after subscriber is closed by error are reported
        - test: observable-constructor.any.worker.html
          subtest: Errors pushed by initializer function after subscriber is closed by error are reported
    - product: firefox
      url: https://bugzilla.mozilla.org/show_bug.cgi?id=1864421
      results:
        - test: observable-constructor.any.worker.html
          subtest: Aborting a subscription should stop emitting values
        - test: observable-constructor.any.worker.html
          subtest: Calling subscribe should never throw an error synchronously, initializer throws error
        - test: observable-constructor.any.worker.html
          subtest: Calling subscribe should never throw an error synchronously, subscriber pushes error
        - test: observable-constructor.any.html
          subtest: Aborting a subscription should stop emitting values
        - test: observable-constructor.any.html
          subtest: Calling subscribe should never throw an error synchronously, initializer throws error
        - test: observable-constructor.any.html
          subtest: Calling subscribe should never throw an error synchronously, subscriber pushes error
    - product: firefox
      url: https://bugzilla.mozilla.org/show_bug.cgi?id=1865858
      results:
        - test: observable-constructor.any.worker.html
          subtest: Subscription is inactive after complete()
        - test: observable-constructor.any.worker.html
          subtest: Subscription is inactive after error()
        - test: observable-constructor.any.worker.html
          subtest: Subscriber#signal is not the same AbortSignal as the one passed into `subscribe()`
        - test: observable-constructor.any.worker.html
          subtest: Subscriber#complete() cannot re-entrantly invoke itself
        - test: observable-constructor.any.worker.html
          subtest: Subscriber#error() cannot re-entrantly invoke itself
        - test: observable-constructor.any.html
          subtest: Subscription is inactive after complete()
        - test: observable-constructor.any.html
          subtest: Subscription is inactive after error()
        - test: observable-constructor.any.html
          subtest: Subscriber#signal is not the same AbortSignal as the one passed into `subscribe()`
        - test: observable-constructor.any.html
          subtest: Subscriber#complete() cannot re-entrantly invoke itself
        - test: observable-constructor.any.html
          subtest: Subscriber#error() cannot re-entrantly invoke itself
    - product: firefox
      url: https://bugzilla.mozilla.org/show_bug.cgi?id=1868520
      results:
        - test: observable-constructor.any.html
          subtest: Subscription is inactive when aborted signal is passed in
        - test: observable-constructor.any.html
          subtest: Unsubscription lifecycle
        - test: observable-constructor.any.html
          subtest: Teardown should be called when subscription is aborted
        - test: observable-constructor.any.html
          subtest: Teardowns should be called when subscription is closed by completion
        - test: observable-constructor.any.html
          subtest: Teardowns should be called when subscription is closed by subscriber pushing an error
        - test: observable-constructor.any.html
          subtest: Teardowns should be called when subscription is closed by subscriber throwing error
        - test: observable-constructor.any.html
          subtest: Teardowns should be called synchronously during addTeardown() if the subscription is inactive
        - test: observable-constructor.any.worker.html
          subtest: Subscription is inactive when aborted signal is passed in
        - test: observable-constructor.any.worker.html
          subtest: Unsubscription lifecycle
        - test: observable-constructor.any.worker.html
          subtest: Teardown should be called when subscription is aborted
        - test: observable-constructor.any.worker.html
          subtest: Teardowns should be called when subscription is closed by completion
        - test: observable-constructor.any.worker.html
          subtest: Teardowns should be called when subscription is closed by subscriber pushing an error
        - test: observable-constructor.any.worker.html
          subtest: Teardowns should be called when subscription is closed by subscriber throwing error
        - test: observable-constructor.any.worker.html
          subtest: Teardowns should be called synchronously during addTeardown() if the subscription is inactive
    - product: firefox
      url: https://bugzilla.mozilla.org/show_bug.cgi?id=1870088
      results:
        - test: observable-constructor.window.html
          subtest: No observer handlers can be invoked in detached document
        - test: observable-constructor.window.html
          subtest: Subscriber.error() does not "report the exception" even when an `error()` handler is not present, when it is invoked in a detached document
        - test: observable-constructor.window.html
          subtest: Cannot subscribe to an Observable in a detached document
    - product: firefox
      url: https://bugzilla.mozilla.org/show_bug.cgi?id=1873568
      results:
        - test: observable-event-target.window.html
          subtest: EventTarget Observables can be 'passive'
    - product: firefox
      url: https://bugzilla.mozilla.org/show_bug.cgi?id=1871732
      results:
        - test: observable-constructor.window.html
        - test: observable-event-target.any.html
        - test: observable-event-target.any.worker.html
        - test: observable-event-target.window.html
        - test: observable-constructor.any.html
        - test: observable-constructor.any.worker.html
    - product: safari
      url: https://bugs.webkit.org/show_bug.cgi?id=266843
      results:
        - test: observable-constructor.any.html
        - test: observable-constructor.any.worker.html
        - test: observable-constructor.window.html
        - test: observable-event-target.any.html
        - test: observable-event-target.any.worker.html
        - test: observable-event-target.window.html
