links:
    - product: firefox
      url: https://bugzilla.mozilla.org/show_bug.cgi?id=1841786
      results:
        - test: remote_values.py
          subtest: test_remote_values[[1, 2][Symbol.iterator]()-expected15]
        - test: remote_values.py
          subtest: test_remote_values['mystring'[Symbol.iterator]()-expected16]
        - test: remote_values.py
          subtest: test_remote_values[(new Set([1,2]))[Symbol.iterator]()-expected17]
        - test: remote_values.py
          subtest: test_remote_values[(new Map([[1,2]]))[Symbol.iterator]()-expected18]
        - test: remote_values.py
          subtest: test_remote_values[new Proxy({}, {})-expected19]
        - test: remote_values.py
          subtest: test_remote_values[(function*() { yield 'a'; })()-expected20]
        - test: exception_details.py
          subtest: test_exception_details[[1, 2][Symbol.iterator]()-expected28]
        - test: exception_details.py
          subtest: test_exception_details['mystring'[Symbol.iterator]()-expected29]
        - test: exception_details.py
          subtest: test_exception_details[(new Set([1,2]))[Symbol.iterator]()-expected30]
        - test: exception_details.py
          subtest: test_exception_details[(new Map([[1,2]]))[Symbol.iterator]()-expected31]
        - test: exception_details.py
          subtest: test_exception_details[new Proxy({}, {})-expected32]
        - test: exception_details.py
          subtest: test_exception_details[(function*() { yield 'a'; })()-expected33]
        - test: exception_details_await_promise.py
          subtest: test_exception_details_await_promise[[1, 2][Symbol.iterator]()-expected28]
        - test: exception_details_await_promise.py
          subtest: test_exception_details_await_promise['mystring'[Symbol.iterator]()-expected29]
        - test: exception_details_await_promise.py
          subtest: test_exception_details_await_promise[(new Set([1,2]))[Symbol.iterator]()-expected30]
        - test: exception_details_await_promise.py
          subtest: test_exception_details_await_promise[(new Map([[1,2]]))[Symbol.iterator]()-expected31]
        - test: exception_details_await_promise.py
          subtest: test_exception_details_await_promise[new Proxy({}, {})-expected32]
        - test: exception_details_await_promise.py
          subtest: test_exception_details_await_promise[(function*() { yield 'a'; })()-expected33]
